name = "snow-school-scheduler"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# D1データベースバインディング
[[d1_databases]]
binding = "DB"
database_name = "snow-school-scheduler"
database_id = "a39eae08-e034-45a3-b85a-d7e9d1b57c30"

# 環境変数（非機密情報のみ）
[vars]
NODE_ENV = "production"
