name = "snow-school-scheduler-api"
main = "dist/index.js"
compatibility_date = "2024-06-01"

[[d1_databases]]
binding = "DB"
database_name = "snow-school-scheduler"
database_id = ""

[env.production]
name = "snow-school-scheduler-api"

[env.development]
name = "snow-school-scheduler-api-dev"