name: Manual Seed Execution

on:
  workflow_dispatch:
    inputs:
      seed_file:
        description: 'Select a seed file from prisma/seeds-prod/'
        required: true
        type: choice
        # prisma/seeds-prod にファイルを追加したら新しい順でここに登録すること。
        options:
          - 01_initial_master_data.ts

jobs:
  seed:
    runs-on: ubuntu-latest
    if: github.repository == 'keichan110/snow-school-scheduler'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Load D1_DATABASE_ID from wrangler.toml
        id: load_d1_database_id
        run: |
          value=$(node scripts/get-wrangler-config.js 'd1_databases.0.database_id')
          echo "D1_DATABASE_ID=$value" >> "$GITHUB_ENV"

      - name: Validate selected seed file
        run: |
          seed_file="${{ github.event.inputs.seed_file }}"
          if [[ ! -f "prisma/seeds-prod/$seed_file" ]]; then
            echo 'Invalid seed file. Available choices:'
            ls prisma/seeds-prod
            exit 1
          fi

      - name: Apply production seed data
        id: seed
        run: npm run db:seed:prod -- prisma/seeds-prod/${{ github.event.inputs.seed_file }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          DATABASE_URL: 'wrangler://api.cloudflare.com/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/d1/databases/${{ env.D1_DATABASE_ID }}'

      - name: Notify on failure
        if: failure()
        run: |
          echo "Manual seed execution failed for file: ${{ github.event.inputs.seed_file }}"
          exit 1

      - name: Notify on success
        if: success()
        run: |
          echo "✅ Manual seed execution successful for file: ${{ github.event.inputs.seed_file }}"
